#define ID_EMPTY        0
#define ID_IDENTITER    1
#define ID_CONSTANT     2
#define ID_INT          3
#define ID_IF           4
#define ID_ELSE         5
#define ID_WHILE        6
#define ID_FOR          7
#define ID_READ         8
#define ID_WRITE        9
#define ID_PLUS         10
#define ID_SUB          11
#define ID_MUL          12
#define ID_DIV          13
#define ID_LT           14
#define ID_LE           15
#define ID_GT           16
#define ID_GE           17
#define ID_NE           18
#define ID_EQ           19
#define ID_ASSIGN       20
#define ID_LBRACKET     21
#define ID_RBRACKET     22
#define ID_COMMA        23
#define ID_SEMICOLON    24
#define ID_BIG_LBRACKET 25
#define ID_BIG_RBRACKET 26
#define ID_RETURN       27
#define ID_BREAK        28
#define ID_CONTINUE     29
#define ID_LAND         30
#define ID_LOR          31
#define ID_BAND         32
#define ID_BOR          33
#define ID_NOT          34
#define ID_XOR          35
#define ID_LS           36
#define ID_RS           37
#define ID_MID_LBRACKET 38
#define ID_MID_RBRACKET 39